baseURL: http://localhost:1313/
locale: en-us
title: Favian Flores
theme: Celadon

params:
  homepage:
    sections: [hero, projects]
    projects:
      enable: true
      title: Projects
      layout: cards
